#!/bin/zsh -l
#SBATCH -J spawn-multi
#SBATCH --gres=gpu:{{NUM_GPUS}}
#SBATCH -c {{NUM_CPUS}}
#SBATCH -t 2-11:59
#SBATCH -p gpu
#SBATCH --mem=32000
#SBATCH -o /n/home04/hbalim/outputs/%j.out
#SBATCH -e /n/home04/hbalim/outputs/%j.err

lmods
#mamba activate d4rl
#mamba activate dsrl
vact
export XDG_RUNTIME_DIR=

bash "{{COMMAND_SCRIPT}}"
